// Code generated by "stringer -type NebulaMessageType,NebulaMessageSubType"; DO NOT EDIT.

package nebula

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[handshake-0]
	_ = x[message-1]
	_ = x[recvError-2]
	_ = x[lightHouse-3]
	_ = x[test-4]
	_ = x[closeTunnel-5]
	_ = x[proxy-8]
}

const (
	_NebulaMessageType_name_0 = "handshakemessagerecvErrorlightHousetestcloseTunnel"
	_NebulaMessageType_name_1 = "proxy"
)

var (
	_NebulaMessageType_index_0 = [...]uint8{0, 9, 16, 25, 35, 39, 50}
)

func (i NebulaMessageType) String() string {
	switch {
	case i <= 5:
		return _NebulaMessageType_name_0[_NebulaMessageType_index_0[i]:_NebulaMessageType_index_0[i+1]]
	case i == 8:
		return _NebulaMessageType_name_1
	default:
		return "NebulaMessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[testRequest-0]
	_ = x[testReply-1]
	_ = x[handshakeIXPSK0-2]
	_ = x[handshakeXXPSK0-3]
}

const _NebulaMessageSubType_name = "testRequesttestReplyhandshakeIXPSK0handshakeXXPSK0"

var _NebulaMessageSubType_index = [...]uint8{0, 11, 20, 35, 50}

func (i NebulaMessageSubType) String() string {
	if i >= NebulaMessageSubType(len(_NebulaMessageSubType_index)-1) {
		return "NebulaMessageSubType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NebulaMessageSubType_name[_NebulaMessageSubType_index[i]:_NebulaMessageSubType_index[i+1]]
}
